### ISSUE TITLE
lit-element package on npm

### ISSUE THREAD

**Issue by justinfagnani** [Molecule-JS/MoleculeJS#16]
Hi there @DiiLord!

I'm always happy to see more Web Components base classes built with lit-html 👍and appreciate that you lead the way with your LitElement version before the Polymer team got ours ready. Now that you've renamed to MoleculeJS (which I does think reduces confusion), what do you think about the lit-element package name on npm? Having `@polymer/lit-element` be unscoped would be nice for us.

Thanks!

**Comment by DerDrodt** [comment]
Hello to you, too!

Of course you can have the `lit-element` package, I won't be using it anyway now.

But I don't have a lot of experience with npm, so it would be really helpful, if you could walk me through the steps necessary to tranfer the ownership.

Thanks

**Comment by justinfagnani** [comment]
That's great to hear! Can you email me at my github username @ google.com?

**Comment by DerDrodt** [comment]
Just did.
